# Generated by Django 3.0.4 on 2020-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='headline',
            field=models.CharField(default='Report', max_length=250),
        ),
    ]
